### ISSUE TITLE
Cannot print vars

### ISSUE THREAD

**Issue by raffaelecolleo** [jdotjdot/BashWeather#7]
Hy Everyone,
I'm trying to add this to a script I'm building to control the weather in my region and add to database.

After download the file I've created a file but I cannot see the data.

Here is my file:
# !/bin/bash

/var/www/scripts/BashWeather.sh -l "London,UK"
myvars=$WEATHERCHAR
echo $myvars

Can someone help me?

Thank You
Raffaele Colleo

**Comment by jdotjdot** [comment]
@raffaelecolleo This is fixed with the two most recent commits.

First, it turns out there was an issue with the API call by city name to get the weather character. With dccb1dc2cd6a27afc0efcc4d62ae2372f76aeeef (url-escaping), it should now work with the flag `-l "London, UK"`.

Second, I've added an `-e` flag that will echo the result instead of saving to `WEATHERCHAR`.  This way you can more easily get the result as you desire like so:

```bash
myvars=$(/var/www/scripts/BashWeather.sh -l "London,UK" -e)
echo $myvars
```
